name: MultipleJobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
      run: echo "The build step"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
      run: echo "The test step"
  
  
