name: Multiple_Jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "The build job"
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "The test job"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "The deploy job"
